# Generated by Django 3.1.3 on 2020-11-14 12:48

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('surburb', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=30)),
                ('max_guest', models.IntegerField()),
                ('guest_price_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_guest_price_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(upload_to='pictures/')),
                ('property_image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_cloudbnb.property')),
            ],
        ),
    ]
